const CONFIG = {
  apiKey: "YOUR_GOOGLE_SHEETS_API_KEY",
  sheets: [
    {
      id: "1-TVQ7YdR90d_7DFZXAKqARLe7KjKMz25",
      sheet: "Inventory Monitoring",
      name: "Janitorial Supplies",
      color: "#3b82f6",
      columns: {
        code: 0,
        item: 1,
        stock: 2,
        reorderPoint: 3,
        inStock: 5,
        lowStock: 6,
        outOfStock: 7,
      },
    },
    {
      id: "1GNWyQwN1OLWSGIbaRAO2s2xHHEpXJ6uq",
      sheet: "Inventory Monitoring",
      name: "Instructional Supplies",
      color: "#8b5cf6",
      columns: {
        code: 0,
        item: 1,
        stock: 2,
        reorderPoint: 3,
        inStock: 5,
        lowStock: 6,
        outOfStock: 7,
      },
    },
    {
      id: "1i7n9FjKJrVDXv3G7KXvULV-fm9RTpSnU",
      sheet: "Inventory Monitoring",
      name: "Office Supplies",
      color: "#10b981",
      columns: {
        code: 0,
        item: 1,
        stock: 2,
        reorderPoint: 3,
        inStock: 5,
        lowStock: 6,
        outOfStock: 7,
      },
    },
  ],
  refreshIntervalMs: 300000,
};
